name: Server

on:
  push:
    branches:
      - main
    paths:
      - "server/**"
      - ".github/workflows/server-ci.yml"

  pull_request:
    paths:
      - "server/**"
      - ".github/workflows/server-ci.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
          working-directory: server
      - name: Run RSpec
        run: bundle exec rspec
      - name: Run RuboCop
        run: bundle exec rubocop
